### ISSUE TITLE
Machines decides to shutdown on F25

### ISSUE THREAD

**Issue by aruiz** [fleet-commander/fc-admin#136]
When trying to boot a VM on F25 it suddenly shuts itself down in a few seconds

![screenshot from 2016-09-12 17-26-05](https://cloud.githubusercontent.com/assets/2845/18443727/1dab0e50-790e-11e6-9712-f9e3f28c908f.png)

**Comment by olivergs** [comment]
This happens all the time or only sometimes?

**Comment by aruiz** [comment]
Every time, this is what I've been able to gather from the logs:

Sep 12 20:06:43 raynor virtlogd[30391]: End of file while reading data: Input/output error
Sep 12 20:06:43 raynor python[31666]: libvirt: QEMU Driver error : Domain not found: no domain with matching uuid '311616cb-7f8a-4130-99f3-3c434b96e925' (fc-311616cb)

**Comment by olivergs** [comment]
The problem is that for an unknown reason the monitor for stalled machines is not being reset by browser queries. I've to dig a bit more in the problem.

**Comment by olivergs** [comment]
Ok. I've found the real reason behind all this.

If you connect to a libvirt machine that also have fleet commander installed and has the dbus service up and running, that fleet commander will find virtual machines opened by other fleet commander admin hosts, and because that host is not communicating with the libvirt machine's fleet commander, it stops them as soon as the counter reachs 60 seconds (or less if you started the machine in middle of the count).

It's kind of cornercase, but prefer to know your oppinion about this.

**Comment by olivergs** [comment]
This has been fixed when we ported the dbus service to be a session dbus service. The service stops when it is not being used and this can only happen if you open two fleet commander admin sessions to the same libvirt machine with same settings.

Fleet commander is not intended right now as a multiuser environment.
