### ISSUE TITLE
fleet-commander-admin service fails to start

### ISSUE THREAD

**Issue by kclevenger** [fleet-commander/fc-admin#142]
Enabled  rhel-7-server-extras-rpms, Installed cockpit but failed to start up due to selinux being disabled.
Enabled selinux and started cockpit fine. Got the web browser access to https://servername:9090 Can log in. 

Setting up fleet-commander-admin in the same server, latest package is installed now
[root@host yum.repos.d]# rpm -q fleet-commander-admin
fleet-commander-admin-0.7.99-2.el7.centos.noarch

But fleet-commander-admin service fails to start. 

[root@host yum.repos.d]# systemctl status fleet-commander-admin
● fleet-commander-admin.service - Fleet Commander dbus service
   Loaded: loaded (/usr/lib/systemd/system/fleet-commander-admin.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2016-10-11 11:50:54 IST; 1s ago
  Process: 6696 ExecStart=/usr/bin/python -m fleetcommander.fcdbus --configuration /etc/xdg/fleet-commander-admin.conf (code=exited, status=1/FAILURE)
 Main PID: 6696 (code=exited, status=1/FAILURE)

Oct 11 11:50:54 host.example.net systemd[1]: Starting Fleet Commander dbus service...
Oct 11 11:50:54 host.example.net systemd[1]: Started Fleet Commander dbus service.
Oct 11 11:50:54 host.example.net python[6696]: FC: [ERROR] Error starting webservice: type object 'InetSocketAddress' has no attribute 'new_from_string'
Oct 11 11:50:54 host.example.net systemd[1]: fleet-commander-admin.service: main process exited, code=exited, status=1/FAILURE
Oct 11 11:50:54 host.example.net systemd[1]: Unit fleet-commander-admin.service entered failed state.
Oct 11 11:50:54 host.example.net systemd[1]: fleet-commander-admin.service failed.

When accessing via https://servername:9090 and go to link Fleetcommander , get an oops message :- 

Unexpected error
Cockpit had an unexpected internal error. 
You can try restarting Cockpit by pressing refresh in your browser. The javascript console contains details about this error (Ctrl-Shift-J in most browsers).

**Comment by olivergs** [comment]
We need some more information to debug this problem:

RHEL version
pygobject package version

**Comment by kclevenger** [comment]
I have asked for a sosreport from the host. I will make it available as soon as I get it.

**Comment by kclevenger** [comment]
I've emailed you the location of the sosreport

**Comment by kclevenger** [comment]
Here's the sosreport from the Dreamworks host

http://people.redhat.com/~kcleveng/.01423587/sosreport-evenave.blr.dreamworks.net.CASE01423587-20161019145102.tar.xz



Thanks

Kevin

--

Kevin Clevenger, RHCE
Technical Account Manager
Desk: 650.254.4184
Red Hat, Inc.

**Comment by olivergs** [comment]
Thank you. We will take a look to it ASAP

**Comment by kclevenger** [comment]
Is there any update on this?

**Comment by aruiz** [comment]
Hey Kevin, Oliver should be back from vacation next week and get to this right away.

**Comment by olivergs** [comment]
Hi Kevin.

I've been checking the SOS report and found the following:

* The SOS report is for a RHEL Workstation machine. Fleet commander admin is intended to be installed in a RHEL server machine, and the reason is simple: Cockpit is not included in RHEL workstation. Is included in RHEL server extras, so you need to enable that repository as well as the COPR for fleet commander.

* Neither fleet-commander-admin nor cockpit is in the SOS report package list, and I found there are files from an older copr, related to an older fleet commander version.

I think probably there was a mistake in the steps for the installation so I will explain them for installing fleet commander admin in RHEL Server 7.2. Please follow this steps:

* Enable rhel-server-extras repository 
    `sudo subscription-manager repos --enable rhel-7-server-extras-rpms`
* Add the fleet commander EL7 copr repo
```
cd /etc/yum.repos.d
sudo wget https://copr.fedorainfracloud.org/coprs/aruiz/fleet-commander-el7/repo/epel-7/aruiz-fleet-commander-el7-epel-7.repo
```
* Update RHEL server and install fleet-commander-admin
```
sudo yum update
sudo yum install fleet-commander-admin
```
* Make sure cockpit is active (fleet-commander-admin is dbus activated, but can be started manually if you want)
* Open the firewall if necessary
```
sudo firewall-cmd --add-service=cockpit
sudo firewall-cmd --add-service=cockpit --permanent
sudo firewall-cmd --add-port=9989/tcp
```

And that's it. Anyway, I pass you the GNOME wiki project page with information about installation and basic use, and the copr page.
* https://wiki.gnome.org/Projects/FleetCommander
* https://copr.fedorainfracloud.org/coprs/aruiz/fleet-commander-el7/

If you need some help, don't hesitate to contact us again.

**Comment by kclevenger** [comment]
Here's the latest. Apparently the wrong sosreport was given to me. I'll email you the URL to it.

Thanks

Kevin

[root@host ~]#  systemctl status fleet-commander-admin
● fleet-commander-admin.service - Fleet Commander dbus service
   Loaded: loaded (/usr/lib/systemd/system/fleet-commander-admin.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-11-02 12:09:51 IST; 1s ago
  Process: 7086 ExecStart=/usr/bin/python -m fleetcommander.fcdbus --configuration /etc/xdg/fleet-commander-admin.conf (code=exited, status=1/FAILURE)
 Main PID: 7086 (code=exited, status=1/FAILURE)

Nov 02 12:09:50 host.example.net systemd[1]: Starting Fleet Commander dbus service...
Nov 02 12:09:51 host.example.net systemd[1]: Started Fleet Commander dbus service.
Nov 02 12:09:51 host.example.net python[7086]: FC: [ERROR] Error starting webservice: type object 'InetSocketAddress' h...ring'
Nov 02 12:09:51 host.example.net systemd[1]: fleet-commander-admin.service: main process exited, code=exited, status=1/FAILURE
Nov 02 12:09:51 host.example.net systemd[1]: Unit fleet-commander-admin.service entered failed state.
Nov 02 12:09:51 host.example.net systemd[1]: fleet-commander-admin.service failed

**Comment by olivergs** [comment]
Hi Kevin. Seems that the problem comes because the machine is not updated. The version they have installed for  pygobject packages etc is way lower than the updated versions 3.8 vs 3.14 in pygobject3-base for example.

Please, update the libraries to the latest version and try to run the service. It should work after updating the system.

**Comment by olivergs** [comment]
Closed due to inactivity
